name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build

      - name: Create .nojekyll file
        run: touch build/.nojekyll

      - name: Setup custom _headers file
        run: |
          echo "/*" > build/_headers
          echo "  Cache-Control: public, max-age=3600" >> build/_headers
          echo "/assets/*" >> build/_headers
          echo "  Cache-Control: public, max-age=31536000, immutable" >> build/_headers
          echo "/_app/immutable/*" >> build/_headers
          echo "  Cache-Control: public, max-age=31536000, immutable" >> build/_headers
          echo "/_app/version.json" >> build/_headers
          echo "  Cache-Control: public, max-age=0, must-revalidate" >> build/_headers

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
